async:
  task:
    enable: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/async-task?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root